version: "3.8"
services:
  db:
    image: postgres
    container_name: pg_database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nqode
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata: